/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include<android/log.h>
#include <stdlib.h>
/* Header for class com_example_xiaoqiang_myapplication_jni_LibX264 */

#ifndef _Included_com_example_xiaoqiang_myapplication_jni_LibX264
#define _Included_com_example_xiaoqiang_myapplication_jni_LibX264
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_xiaoqiang_myapplication_jni_LibX264
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_xiaoqiang_myapplication_jni_LibX264_init
  (JNIEnv *, jobject);

/*
 * Class:     com_example_xiaoqiang_myapplication_jni_LibX264
 * Method:    encoded
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_xiaoqiang_myapplication_jni_LibX264_encoded
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_example_xiaoqiang_myapplication_jni_LibX264
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_xiaoqiang_myapplication_jni_LibX264_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
